name: Build the service docker images
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build API
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./api
          builder: ${{ steps.buildx.outputs.name }}
          push: false
      # TODO: Build Frontend Docker
