name: build-and-test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install virtualenv
        run: pip install virtualenv

      - name: install deps
        run: ./bin/install.sh

      - name: Start the backend
        run: ./bin/start-api.sh &

      - name: Wait for download to finish
        run: sleep 5

      - name: Test backend
        run: ./bin/test-backend.sh

      - name: Run the linter
        run: ./bin/lint.sh
