name: Dev Example React Demo Deployment
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# See: https://github.com/marketplace/actions/amplify-cli-action
jobs:
  test:
    name: test amplify-cli-action
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: configure amplify
        uses: ambientlight/amplify-cli-action@0.2.2
        with:
          amplify_command: configure
          amplify_env: dev
          project_dir: ./examples/react-amplified
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2

      - name: install, build and test
        working-directory: ./examples/react-amplified
        run: |
          npm install
          # build and test
          # npm run build
          # npm run test

      - name: deploy
        uses: ambientlight/amplify-cli-action@0.2.2
        with:
          amplify_command: publish
          amplify_env: dev
          project_dir: ./examples/react-amplified
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
