name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the docker-compose stack
        run: docker-compose up -d

      - name: Install virtualenv
        run: pip install virtualenv

      - name: Test backend
        run: sleep 10 && cd ./api && ./test.sh


